# Generated by Django 4.2.4 on 2023-08-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchResults',
            new_name='MatchResult',
        ),
    ]
