# Generated by Django 4.2.4 on 2023-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0002_rename_matchresults_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='documentCSV',
            field=models.FileField(upload_to='sports_league/documentCSV/'),
        ),
    ]
