# Generated by Django 4.2.4 on 2023-08-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0003_alter_matchresult_documentcsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
