# Generated by Django 4.2.4 on 2023-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_league', '0004_delete_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('resultID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('documentCSV', models.FileField(upload_to='sports_league/documentCSV/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
