# Generated by Django 4.2.4 on 2023-08-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
