# Generated by Django 4.2.4 on 2023-08-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_league', '0011_delete_match_delete_matchresult_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult_File',
            fields=[
                ('resultID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('documentCSV', models.FileField(upload_to='sports_league/documentCSV/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamOne', models.CharField(max_length=200)),
                ('teamTwo', models.CharField(max_length=200)),
                ('teamOneScore', models.IntegerField()),
                ('teamTwoScore', models.IntegerField()),
                ('resultFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_league.matchresult_file')),
            ],
        ),
    ]
