# Generated by Django 4.2.4 on 2023-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0013_alter_matchresult_file_resultid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult_file',
            name='resultID',
            field=models.CharField(default='placeholderID', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
