# Generated by Django 4.2.4 on 2023-08-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0016_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
