# Generated by Django 4.2.4 on 2023-08-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0018_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='resultFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_league.matchresult_file'),
        ),
    ]
