# Generated by Django 4.2.4 on 2023-08-13 11:28

from django.db import migrations, models
import sports_league.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sports_league', '0019_alter_rank_resultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult_file',
            name='documentCSV',
            field=models.FileField(storage=sports_league.storage.OverwriteStorage(), upload_to='sports_league/documentCSV/'),
        ),
    ]
