# Generated by Django 4.2.4 on 2023-08-13 11:32

from django.db import migrations, models
import django.db.models.deletion
import sports_league.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_league', '0021_remove_rank_resultfile_delete_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult_File',
            fields=[
                ('resultID', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('documentCSV', models.FileField(storage=sports_league.storage.OverwriteStorage(), upload_to='sports_league/documentCSV/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('resultFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_league.matchresult_file')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamOne', models.CharField(max_length=200)),
                ('teamTwo', models.CharField(max_length=200)),
                ('teamOneScore', models.IntegerField()),
                ('teamTwoScore', models.IntegerField()),
                ('resultFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_league.matchresult_file')),
            ],
        ),
    ]
